# Generated by Django 3.2 on 2021-04-29 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=60, unique=True)),
                ('city', models.CharField(blank=True, max_length=45, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('creating_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=60, null=True)),
                ('first_name', models.CharField(max_length=45, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=60, null=True)),
                ('mob_phone', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('sec_phone', models.CharField(blank=True, max_length=11, null=True)),
                ('e_mail', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('city', models.CharField(blank=True, default='Москва', max_length=45, null=True)),
                ('messenger', models.CharField(blank=True, max_length=45, null=True)),
                ('messenger_id', models.CharField(blank=True, max_length=120, null=True)),
                ('position', models.CharField(blank=True, max_length=120, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='')),
                ('creating_date', models.DateTimeField(blank=True, null=True)),
                ('current_company', models.ForeignKey(blank=True, db_column='company_name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_company', to='my_db.company', to_field='company_name')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy', models.CharField(blank=True, max_length=120, null=True)),
                ('project_name', models.CharField(blank=True, max_length=120, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('creating_date', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, db_column='company_name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_company', to='my_db.company', to_field='company_name')),
            ],
        ),
        migrations.CreateModel(
            name='Projects_People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('TK', 'to call'), ('II', 'invited for interview'), ('IC', 'interview with client'), ('CR', 'candidate refused'), ('CP', 'candidate to present'), ('RS', 'resume sent'), ('CV', 'considering vacancy')], max_length=2, null=True)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='long_list_persons', to='my_db.person')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='long_list_project', to='my_db.project')),
            ],
        ),
    ]
