# Generated by Django 3.2 on 2021-04-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(default='Moscow', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='e_mail',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='messenger',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='messenger_id',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='mob_phone',
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='resume',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='sec_phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='vacancy',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
