# Generated by Django 3.2 on 2021-04-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_db', '0002_auto_20210413_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
